name: Cleanup PR

on:
  pull_request:
    branches:
      - master
    types: [closed]
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR Number (for manual cleanups)"
        required: false
        default: "0"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Determine PR Number
        id: pr_number
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            PR_NUMBER=${{ github.event.pull_request.number }}
          else
            PR_NUMBER=${{ github.event.inputs.pr_number }}
          fi
          echo "BUCKET_NAME=webrtc-pr-$PR_NUMBER.edwardwei.com" >> $GITHUB_ENV
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Remove S3 bucket
        run: |
          aws s3 rb s3://$BUCKET_NAME --force
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
